//
// Generated file, do not edit! Created by opp_msgc 4.3 from base/messages/MiximAirFrame.msg.
//

#ifndef _MIXIMAIRFRAME_M_H_
#define _MIXIMAIRFRAME_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0403
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "Signal_.h"
// }}



/**
 * Class generated from <tt>base/messages/MiximAirFrame.msg</tt> by opp_msgc.
 * <pre>
 * packet MiximAirFrame
 * {
 *     Signal signal;		
 * 
 *     simtime_t duration;	
 * 
 *     int state = 1; 		
 *         					
 *         					
 * 
 *     int type = 0;		
 *         					
 * 
 *     long id;			
 * 							
 * 							
 * 	int protocolId;		
 * 	
 * 	int channel;    	
 * }
 * </pre>
 */
class MiximAirFrame : public ::cPacket
{
  protected:
    Signal signal_var;
    simtime_t duration_var;
    int state_var;
    int type_var;
    long id_var;
    int protocolId_var;
    int channel_var;

  private:
    void copy(const MiximAirFrame& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MiximAirFrame&);

  public:
    MiximAirFrame(const char *name=NULL, int kind=0);
    MiximAirFrame(const MiximAirFrame& other);
    virtual ~MiximAirFrame();
    MiximAirFrame& operator=(const MiximAirFrame& other);
    virtual MiximAirFrame *dup() const {return new MiximAirFrame(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual Signal& getSignal();
    virtual const Signal& getSignal() const {return const_cast<MiximAirFrame*>(this)->getSignal();}
    virtual void setSignal(const Signal& signal);
    virtual simtime_t getDuration() const;
    virtual void setDuration(simtime_t duration);
    virtual int getState() const;
    virtual void setState(int state);
    virtual int getType() const;
    virtual void setType(int type);
    virtual long getId() const;
    virtual void setId(long id);
    virtual int getProtocolId() const;
    virtual void setProtocolId(int protocolId);
    virtual int getChannel() const;
    virtual void setChannel(int channel);
};

inline void doPacking(cCommBuffer *b, MiximAirFrame& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, MiximAirFrame& obj) {obj.parsimUnpack(b);}


#endif // _MIXIMAIRFRAME_M_H_
