#! /bin/sh
DIR=`dirname $0`
DIR=`(cd $DIR ; pwd)`/../src

if [ -z "`grep KINET_PROJ $DIR/Makefile`" ]; then
  echo "This example requires that MiXiM is configured to use the INET Framework."
  echo "See examples-inet/README for details."
else
$DIR/run_mixim $*
fi

